### ISSUE TITLE
HomePageを修正

### ISSUE THREAD

**Issue by dancing-amigo** [Recursion-Group-X/bomber-man#13]
### 対処概要
ステージ選択ボタンをなくす
ステージ選択ページをなくす
アバター表示を無くす
ユーザーネームを入力できるようにしてローカルストレージに保存。
その他デザイン、見た目通して変更する

遊び方を軽く説明する。(どのボタンを使うか)
スコア一覧を見れるようにする

**Comment by pimon0807** [comment]
https://www.figma.com/file/aeJ7oDObpps1yMcGaAeFlc/%E7%84%A1%E9%A1%8C?node-id=1%3A2&t=S1vG9NgNYhe2PiJV-1
HomePageのデザイン書いてみました。修正などあれば言ってください！
問題なければ、実装します！
