### ISSUE TITLE
ワイヤーフレーム作成

### ISSUE THREAD

**Issue by dancing-amigo** [Recursion-Group-X/bomber-man#2]
https://whimsical.com/everyone-in-workspace-V2fvD2MRWwGp31f2HJnLq
https://www.figma.com/

Notion
https://www.notion.so/e87a44e9b1084d74a90e24357da49d31

**Comment by pimon0807** [comment]
Figmaを使用してワイヤーフレームを作成しました。
URL:
https://www.figma.com/file/KGKgvpnruZGUJBWiuoxjYR/%E7%84%A1%E9%A1%8C?node-id=0%3A1&t=DuUqmldEed30UaLV-1
メンバー間でのイメージに違いが無いように修正したいと思っています。大きく違う部分があれが修正・変更を加えたいので、一目見て通してもらえると助かります。

**Comment by dancing-amigo** [comment]
> Figmaを使用してワイヤーフレームを作成しました。 URL: https://www.figma.com/file/KGKgvpnruZGUJBWiuoxjYR/%E7%84%A1%E9%A1%8C?node-id=0%3A1&t=DuUqmldEed30UaLV-1 メンバー間でのイメージに違いが無いように修正したいと思っています。大きく違う部分があれが修正・変更を加えたいので、一目見て通してもらえると助かります。

とても良いと思います、ありがとうございます！コメントを少し加えたので確認よろしくお願いします！

**Comment by pimon0807** [comment]
> とても良いと思います、ありがとうございます！コメントを少し加えたので確認よろしくお願いします！

コメント確認しました。ありがとうございます！！
修正加えます！
